name: do_it
description: DoIt goup task management application by DudiY and OrM

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: 3.0.5
  # firebase dependencies
  cloud_firestore: 0.7.4
  firebase_auth: 0.5.20
  firebase_messaging: 1.0.5
  firebase_storage: 1.0.2
  flutter_speed_dial: 1.0.8
  uuid: any
  image_picker: 0.4.10
  path_provider: 0.4.1
  cached_network_image: 0.4.2
  flutter_cache_manager: 0.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/loading_profile_pic.png
    - assets/images/unknown_profile_pic.jpg
    - assets/images/default_group_image.jpg
    - assets/icons_and_buttons/podium_icon.png
    - assets/doit_logo/loading_animation.gif
    - assets/logo_with_shadow.png
    - assets/icons_and_buttons/google_icon.png
    - assets/images/click_to_create_group.png
    - assets/images/minion_sad.png
    - assets/images/bg_images/blue.jpg
    - assets/images/bg_images/colorful.jpg
    - assets/images/bg_images/leaves.jpg
    - assets/images/bg_images/lights.jpg
    - assets/images/bg_images/orange_sky.jpg
    - assets/images/bg_images/paper.jpg
    - assets/images/bg_images/pink.jpg
    - assets/images/bg_images/polygons.jpg
    - assets/images/bg_images/underwater.jpg
    - assets/images/bg_images/wood.jpg
    - assets/images/bg_images/green_circuit.png
    - assets/images/bg_images/red_sun.jpg
    - assets/images/scan_nfc.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
